'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Others

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblErrMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblErrMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEM_CD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEM_CD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtEmpCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmpCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TxtFname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbPayMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPayMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ChkContactEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkContactEnd As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpContactEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpContactEnd As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''TxtBANKACNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBANKACNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkLPromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkLPromo As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpLPromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpLPromo As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''TxtPFNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPFNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkLInc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkLInc As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpLInc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpLInc As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''TxtESINO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtESINO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkLAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkLAppraisal As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpLAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpLAppraisal As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''TxtPANNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPANNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkGrpJoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkGrpJoin As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpGrpJoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpGrpJoin As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''TxtTANNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTANNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJOBPROFILE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJOBPROFILE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbLeaveType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLeaveType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LblDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDate1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkNotice As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpNotice As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''LblDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDate2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkDOL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkDOL As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpDOL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpDOL As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''LblDate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDate3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkSettle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSettle As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpSettle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpSettle As Global.DITWebLibrary.DTPCombo

    '''<summary>
    '''LblNewOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNewOrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNewOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNewOrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtLReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LblRights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblRights As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Txtdtp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtdtp As Global.System.Web.UI.WebControls.TextBox
End Class
