USE ERELIANCE

select * from WEBUSERS
SELECT * FROM ReportsType
SP_HELP ACCESSTABLE
select * from   accesstable ORDER BY 2

select * from COSTMAST
SELECT * FROM JOBMAST

select * from LOCMAST
select * from EMPTYPE
SELECT * FROM EMPCLASSMAST

SELECT * FROM DIVIMAST
SELECT * FROM GRDMAST
SELECT * FROM COSTTYPEMAST
SELECT * FROM BUnitMast
SELECT * FROM ContractType


Select Tab_Name,Tab_Desc,Code,Description, ShortCut From AccessTable ORDER BY 1  SHORTCUT

INSERT INTO ACCESSTABLE VALUES('11','LOCMAST','Work Location','LOC_CODE','LOC_NAME','W')
INSERT INTO ACCESSTABLE VALUES('12','LOCMAST','Admin Location','LOC_CODE','LOC_NAME','A')
DELETE ACCESSTABLE WHERE TAB_ID=11
DELETE ACCESSTABLE WHERE TAB_ID=12
update accesstable set tab_desc='Pay Location' where tab_id='7'
INSERT INTO ACCESSTABLE VALUES('13','JOBMAST','Job Master','JOB_CODE','JOB_DESC','O')
INSERT INTO ACCESSTABLE VALUES('14','EMPCLASSMAST','Employee Class','EMP_CLASS','EMP_DESC','E')
INSERT INTO ACCESSTABLE VALUES('15','COSTTYPEMAST','Costing','COSTTYPE_CODE','COSTTYPE_DESC','Y')
INSERT INTO ACCESSTABLE VALUES('16','BUnitMast','Business Unit','Unit_CODE','UNIT_DESC','B')
INSERT INTO ACCESSTABLE VALUES('17','CONTRACTTYPE','Contract Type','CONT_TYPE','CONT_DESC','F')


