'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestForm

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist224 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist224 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist223 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist223 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist222 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist222 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist221 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist221 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist220 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist220 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist219 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist219 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist218 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist218 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist217 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist217 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist216 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist216 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist215 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist215 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist214 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist214 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist213 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist213 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist212 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist212 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist211 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist211 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist210 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist210 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist209 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist209 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist208 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist208 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist207 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist207 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist206 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist206 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist205 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist205 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist204 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist204 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist203 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist203 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist202 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist202 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist201 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist201 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist200 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist199 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist199 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist198 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist198 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist197 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist197 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist196 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist196 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist195 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist195 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist194 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist194 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist193 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist193 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist192 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist192 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist191 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist191 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist190 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist190 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist189 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist189 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist188 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist188 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist187 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist187 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist186 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist186 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist185 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist185 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist184 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist184 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist183 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist183 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist182 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist182 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist181 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist181 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist180 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist180 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist179 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist179 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist178 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist178 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist177 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist177 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist176 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist176 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist175 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist175 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist174 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist174 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist173 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist173 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist172 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist172 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist171 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist171 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist170 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist170 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist169 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist169 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist168 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist168 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist167 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist167 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist166 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist166 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist165 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist165 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist164 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist164 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist163 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist163 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist162 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist162 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist161 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist161 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist160 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist160 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist159 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist159 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist158 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist158 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist157 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist157 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist156 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist156 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist155 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist155 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist154 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist154 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist153 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist153 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist152 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist152 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist151 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist151 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist150 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist150 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist149 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist149 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist148 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist148 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist147 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist147 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist146 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist146 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist145 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist145 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist144 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist144 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist143 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist143 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist142 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist142 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist141 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist141 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist140 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist140 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist139 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist139 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist138 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist138 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist137 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist137 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist136 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist136 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist135 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist135 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist134 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist134 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist133 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist133 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist132 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist132 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist131 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist131 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist130 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist130 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist129 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist129 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist128 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist128 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist127 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist127 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist126 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist126 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist125 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist125 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist124 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist124 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist123 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist122 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist122 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist121 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist121 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist120 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist120 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist119 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist119 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist118 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist118 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist117 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist117 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist116 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist116 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist115 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist115 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist114 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist114 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist113 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist113 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist112 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist112 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist111 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist111 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist110 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist110 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist109 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist108 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist108 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist107 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist106 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist105 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist105 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist104 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist104 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist103 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist103 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist102 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist102 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist101 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist101 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist100 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist99 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist98 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist98 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist97 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist97 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist96 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist96 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist95 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist95 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist94 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist94 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist93 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist93 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist92 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist92 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist91 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist91 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist90 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist89 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist89 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist88 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist88 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist87 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist87 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist86 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist86 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist85 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist85 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist84 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist84 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist83 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist83 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist82 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist81 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist81 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist80 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist80 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist79 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist79 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist78 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist78 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist77 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist76 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist75 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist74 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist74 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist73 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist72 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist71 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist71 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist70 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist70 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist69 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist69 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist68 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist68 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist67 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist67 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist66 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist66 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist65 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist65 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist64 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist63 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist62 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist61 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist60 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist59 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist58 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist58 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist57 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist56 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist55 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist54 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist53 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist52 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist51 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist50 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist49 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist48 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist47 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist46 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist45 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist44 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist43 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist42 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist41 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist40 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist39 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist38 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist37 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist36 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist35 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist34 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist33 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist32 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist31 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist30 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist29 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist28 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist27 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist26 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist25 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist24 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist23 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist22 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist21 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist20 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist18 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist17 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist16 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist15 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist14 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist13 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist12 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist11 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Dropdownlist3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
